import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-cyan-600">
          <div className="rounded-1xl bg-gradient-to-br from-pink-200 to-transparent">
            {children}
            
          </div>
        </div>
      </body>
    </html>
  );
}
